-- Multi-square purchasing: one Stripe Checkout Session can claim N squares.
-- Additive migration; existing single-square flow keeps working unchanged.

-- 1. Allow multiple squares to share a stripe_session_id. The original
--    constraint was UNIQUE because one Stripe session = one square; for
--    batches one session = many squares.
drop index if exists public.squares_session_id_idx;
create index if not exists squares_session_id_idx
  on public.squares(stripe_session_id);

-- 2. Group squares paid together. NULL for legacy single-square claims;
--    UUID for batch claims.
alter table public.squares
  add column if not exists batch_id uuid;

create index if not exists squares_batch_id_idx
  on public.squares(batch_id) where batch_id is not null;

-- 3. Audit table for batch checkouts. The squares table is the source of
--    truth for individual claims; this records the batch as a unit (useful
--    for analytics, refunds, expiry tracking, debugging the no-match-row
--    diagnostic case).
create table if not exists public.checkout_batches (
  id                uuid         primary key default gen_random_uuid(),
  stripe_session_id text         not null,
  status            text         not null check (status in ('pending', 'claimed', 'expired')),
  square_count      smallint     not null check (square_count > 0 and square_count <= 100),
  price_cents       integer      not null check (price_cents > 0),  -- TOTAL for the batch
  pending_until     timestamptz,
  claimed_at        timestamptz,
  created_at        timestamptz  not null default now()
);

create unique index if not exists batches_session_id_idx
  on public.checkout_batches(stripe_session_id);

create index if not exists batches_status_idx
  on public.checkout_batches(status);

-- Server-only access (no policies = no anon access). All writes go through
-- the service-role key on the server, same as squares writes.
alter table public.checkout_batches enable row level security;

-- 4. Atomic batch reservation. Inserts the batch row + N square rows in a
--    single transaction. If any single square is unavailable (active claim
--    or active pending by another batch), the entire transaction rolls
--    back — caller gets nothing partial.
create or replace function public.reserve_squares_batch(
  p_coords           jsonb,         -- [{"x": int, "y": int}, ...]
  p_color            text,
  p_name             text,
  p_link             text,
  p_feeling_category text,
  p_message          text,
  p_batch_id         uuid,          -- generated by caller (route)
  p_session_id       text,          -- real Stripe checkout session id
  p_unit_price_cents integer,       -- per-square price (PRICE_CENTS)
  p_minutes          integer
)
returns uuid                         -- returns batch_id on success
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count          int;
  v_pending_until  timestamptz := now() + make_interval(mins => p_minutes);
  v_coord          jsonb;
  v_x              int;
  v_y              int;
begin
  v_count := jsonb_array_length(p_coords);
  if v_count is null or v_count <= 0 or v_count > 100 then
    raise exception 'invalid_count' using errcode = 'check_violation';
  end if;

  -- Insert batch row first. Will fail if (very rarely) the same session id
  -- is reused — desirable, since it surfaces caller bugs immediately.
  insert into public.checkout_batches
    (id, stripe_session_id, status, square_count, price_cents, pending_until)
  values
    (p_batch_id, p_session_id, 'pending', v_count,
     p_unit_price_cents * v_count, v_pending_until);

  -- Reserve each square. The on-conflict-do-update pattern only takes over
  -- a row when its existing reservation has expired. If the WHERE clause
  -- doesn't match (active reservation/claim by someone else), the row
  -- keeps its prior batch_id — which won't equal ours — so we abort.
  for v_coord in select * from jsonb_array_elements(p_coords)
  loop
    v_x := (v_coord->>'x')::int;
    v_y := (v_coord->>'y')::int;

    insert into public.squares
      (x, y, color, name, link, feeling_category, message,
       status, stripe_session_id, batch_id, price_cents, pending_until)
    values
      (v_x, v_y, p_color, p_name, p_link, p_feeling_category, p_message,
       'pending', p_session_id, p_batch_id, p_unit_price_cents, v_pending_until)
    on conflict (x, y) do update
      set color             = excluded.color,
          name              = excluded.name,
          link              = excluded.link,
          feeling_category  = excluded.feeling_category,
          message           = excluded.message,
          stripe_session_id = excluded.stripe_session_id,
          batch_id          = excluded.batch_id,
          price_cents       = excluded.price_cents,
          pending_until     = excluded.pending_until,
          created_at        = now()
      where squares.status = 'pending'
        and squares.pending_until < now();

    -- If the on-conflict's WHERE didn't fire, batch_id is NOT ours.
    -- Abort the whole batch.
    if not exists (
      select 1 from public.squares
      where x = v_x and y = v_y and batch_id = p_batch_id
    ) then
      raise exception 'square_unavailable_at_%_%', v_x, v_y
        using errcode = 'check_violation';
    end if;
  end loop;

  return p_batch_id;
end;
$$;

revoke all on function public.reserve_squares_batch(jsonb,text,text,text,text,text,uuid,text,integer,integer) from public;
revoke all on function public.reserve_squares_batch(jsonb,text,text,text,text,text,uuid,text,integer,integer) from anon, authenticated;
